<?php

/**
 * @file
 * Code for the tweet_link_compile module.
 */

/**
 * Implements hook_cron().
 */
function tweet_link_compile_cron() {
  \Drupal::service('tweet_link_compile.base')->runAll();
}

/**
 * Implements hook_theme().
 */
function tweet_link_compile_theme($existing, $type, $theme, $path) {
  return [
    'tweet_link_compile_page' => [
      'variables' => [
        'text' => NULL,
        'myvariable' => [],
      ],
    ],
  ];
}
